### PR TITLE
touched-up some styling

### PR DESCRIPTION
**Pull request by caseydailey**

### CODE REVIEW

**Comment by caseydailey** [comment]
1) margin on all button groups 
2) removed search button
3) got rid of all the rounded corners

**Comment by wocaldwell** [comment]
Could you update css line 31 to this
 `.profile-image {
	max-width: 300px;
    max-height: 300px;
}`

**Comment by wocaldwell** [comment]
👍

**Comment by wocaldwell** [comment]
Yes!!!!!! 👍

**Pull request merged**
